### ISSUE TITLE
Unable to pull docker image : manifest unknown

### ISSUE THREAD

**Issue by bereldhuin** [heckenmann/docker-swarm-dashboard#339]
Hi,

When i try to pull the master docker image, I got an error "manifest unknown" : 
```
docker pull ghcr.io/heckenmann/docker-swarm-dashboard:master
master: Pulling from heckenmann/docker-swarm-dashboard
```

If I try to pull all images, it seems that there are only 2 tags : 1.2.0 and 1.3.0 : 
```
docker pull -a ghcr.io/heckenmann/docker-swarm-dashboard    
1.2.0: Pulling from heckenmann/docker-swarm-dashboard
59bf1c3509f3: Pull complete 
0258ca7db1f9: Pull complete 
8b93bc798c67: Pull complete 
5b62f4ec289b: Pull complete 
Digest: sha256:68d646bad28e7a597aa11d458d093a67a7c10572b3672f6d0290aa05a4983f41
1.3.0: Pulling from heckenmann/docker-swarm-dashboard
df9b9388f04a: Pull complete 
12755052ad08: Pull complete 
4f4fb700ef54: Pull complete 
6d0a0921895c: Pull complete 
bc811cdb1b93: Pull complete 
Digest: sha256:6d196f4e1856d2be6b9d814889db8e2680734279cf9a98cef6dcd0aac0efa3e9
latest: Pulling from heckenmann/docker-swarm-dashboard
manifest unknown
```

**Comment by heckenmann** [comment]
Hello @bereldhuin ,

thank you very much for your report.

I was able to reproduce the behavior. The issue seems to be with the `container-retention-policy`-action.
The reason is described here: https://github.com/snok/container-retention-policy/issues/63

In this project, the action is disabled until a clean solution is found. The image with the "master"-tag can be downloaded again.

**Comment by heckenmann** [comment]
Older releases (down to version 1.3.0) have been re-uploaded and are now available again.
